### ISSUE TITLE
Suggest using .enableMethodAccessors in the error message when def accessor found

### ISSUE THREAD

**Issue by flicken** [scalalandio/chimney#156]
Full minimal example: https://github.com/flicken/chimney-issue

```
object internal {
  case class Event(venue: Venue)

  sealed trait Venue {
    def name: String
  }

  case class ManuallyFilled(name: String) extends Venue
}

object dto {
 case class Event(venue: Venue)
 case class Venue(name: String)
}

 import io.scalaland.chimney.dsl._
val venue = internal.ManuallyFilled("Venue Name")
val event = internal.Event(venue)

// Compiles on both
venue.transformInto[dto.Venue]
// Fails to compile on 0.5.0, but does on 0.4.2
event.venue.transformInto[dto.Venue]
```

Failure message on 0.5.0:
```
[error] .../chimney-issue/fails/src/main/scala/net/flicken/ChimneyExample.scala:16:35: Chimney can't derive transformation from net.flicken.internal.Venue to net.flicken.dto.Venue
[error] 
[error] net.flicken.dto.Venue
[error]   name: java.lang.String - no accessor named name in source type net.flicken.internal.Venue
[error] 
[error] Consult https://scalalandio.github.io/chimney for usage examples.
[error] 
[error]     println(venue.into[dto.Venue].transform)
[error]                                   ^
[error] one error found
[error] (fails / Compile / compileIncremental) Compilation failed
```

**Comment by krzemin** [comment]
That's a bug indeed.

It seems that derivation fails when upcasted to sealed base type.

```scala
(venue: internal.Venue).transformInto[dto.Venue]
```

This also fails to compile (with the same error message), but it should work.

Thanks for reporting @flicken.

**Comment by krzemin** [comment]
Sorry, I misjudged the example that you provided.

It seems that this behavior is correct according to #128 / #148.

Please use turn your `def name` into `val` or `lazy val`, or enable using method accessors, like:

```scala
event.venue.into[dto.Venue].enableMethodAccessors.transform
```

Read more at https://scalalandio.github.io/chimney/transformers/customizing-transformers.html#using-method-accessors

**Comment by flicken** [comment]
Ah, thanks, I missed that in the release notes.

The compilation error message could be more informative then.  I would expect something like

```
[error] net.flicken.dto.Venue
[error]   name: java.lang.String - no accessor named name in source type net.flicken.internal.Venue, but there was a method with this name
[error]
[error] Use enableMethodAccessors or read more at https://scalalandio.github.io/chimney/transformers/customizing-transformers.html#using-method-accessors
```

**Comment by ldrygala** [comment]
I will take this one
